<?php

namespace Tehla\PumlBundle\Asset\Uml;

use Tehla\PumlBundle\Asset\{
BuildInterface, WrapperInterface, ConstructTrait, BuildTrait
};

/**
* Generated by AssetMaker
* @see AssetMaker
*/
class Note  implements BuildInterface , WrapperInterface
{
use ConstructTrait, BuildTrait;

/** @var array  */
protected $patterns = [
	'note as "Name"',
	'children',
	'end note',
];

/** @var array  */
protected $replaces = [
	'Name' => 'name',
	'children' => '_children_',
];


			
		public static function create(string $desc = '', ?string $name = null): self
		{
		return new static('', $desc, $name);
		}
		
		public function is() :bool
		{
		return $this->type = '';
		}
	



	public function append($child): WrapperInterface
	{
	$this->children->add($child);
	return $this;
	}
}
