<?php

namespace Tehla\PumlBundle\Asset\Archimate;

use Tehla\PumlBundle\Asset\{
BuildInterface, WrapperInterface, ConstructTrait, BuildTrait
};

/**
* Generated by AssetMaker
* @see AssetMaker
*/
class ElementTechnology  implements BuildInterface 
{
use ConstructTrait, BuildTrait;

/** @var array  */
protected $patterns = [
	'Technology_Type(name, "desc")',
];

/** @var array  */
protected $replaces = [
	'Type' => 'type',
	'name' => 'name',
	'desc' => 'desc',
];


			
		public static function createArtifact(string $desc = 'artifact', ?string $name = null): self
		{
		return new static('artifact', $desc, $name);
		}
		
		public function isArtifact() :bool
		{
		return $this->type = 'artifact';
		}
			
		public static function createCollaboration(string $desc = 'collaboration', ?string $name = null): self
		{
		return new static('collaboration', $desc, $name);
		}
		
		public function isCollaboration() :bool
		{
		return $this->type = 'collaboration';
		}
			
		public static function createPath(string $desc = 'path', ?string $name = null): self
		{
		return new static('path', $desc, $name);
		}
		
		public function isPath() :bool
		{
		return $this->type = 'path';
		}
			
		public static function createDevice(string $desc = 'device', ?string $name = null): self
		{
		return new static('device', $desc, $name);
		}
		
		public function isDevice() :bool
		{
		return $this->type = 'device';
		}
			
		public static function createEvent(string $desc = 'event', ?string $name = null): self
		{
		return new static('event', $desc, $name);
		}
		
		public function isEvent() :bool
		{
		return $this->type = 'event';
		}
			
		public static function createFunction(string $desc = 'function', ?string $name = null): self
		{
		return new static('function', $desc, $name);
		}
		
		public function isFunction() :bool
		{
		return $this->type = 'function';
		}
			
		public static function createInterface(string $desc = 'interface', ?string $name = null): self
		{
		return new static('interface', $desc, $name);
		}
		
		public function isInterface() :bool
		{
		return $this->type = 'interface';
		}
			
		public static function createInteraction(string $desc = 'interaction', ?string $name = null): self
		{
		return new static('interaction', $desc, $name);
		}
		
		public function isInteraction() :bool
		{
		return $this->type = 'interaction';
		}
			
		public static function createNode(string $desc = 'node', ?string $name = null): self
		{
		return new static('node', $desc, $name);
		}
		
		public function isNode() :bool
		{
		return $this->type = 'node';
		}
			
		public static function createProcess(string $desc = 'process', ?string $name = null): self
		{
		return new static('process', $desc, $name);
		}
		
		public function isProcess() :bool
		{
		return $this->type = 'process';
		}
			
		public static function createService(string $desc = 'service', ?string $name = null): self
		{
		return new static('service', $desc, $name);
		}
		
		public function isService() :bool
		{
		return $this->type = 'service';
		}
			
		public static function createSystemSoftware(string $desc = 'system-software', ?string $name = null): self
		{
		return new static('system-software', $desc, $name);
		}
		
		public function isSystemSoftware() :bool
		{
		return $this->type = 'system-software';
		}
	



}
