<?php

namespace Tehla\PumlBundle\Asset\Archimate;

use Tehla\PumlBundle\Asset\{
BuildInterface, WrapperInterface, ConstructTrait, BuildTrait
};

/**
* Generated by AssetMaker
* @see AssetMaker
*/
class RelationshipDirectionnal extends Relationship implements BuildInterface 
{
use ConstructTrait, BuildTrait;

/** @var array  */
protected $patterns = [
	'Rel_Type_Direction(from_name, to_name, "desc")',
];

/** @var array  */
protected $replaces = [
	'Type' => 'type',
	'_Direction' => '_direction',
	'from_name' => 'from.name',
	'to_name' => 'to.name',
	'desc' => 'desc',
];

	protected $from, $to, $direction;



						
			public function withFromToDirection($from, $to, $direction): self
			{
							$this->from = $from;
							$this->to = $to;
							$this->direction = $direction;
						return $this;
			}
								public function withDirection($direction): self
			{
			$this->direction = $direction;
			return $this;
			}
			

}
